# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistogram',
            fields=[
                ('filename', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num_bands', models.IntegerField()),
                ('total_pixels', models.IntegerField()),
                ('red_band', models.IntegerField()),
                ('green_band', models.IntegerField()),
                ('blue_band', models.IntegerField()),
                ('alpha_band', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
