# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehistogram',
            name='alpha_band',
        ),
        migrations.RemoveField(
            model_name='imagehistogram',
            name='blue_band',
        ),
        migrations.RemoveField(
            model_name='imagehistogram',
            name='green_band',
        ),
        migrations.RemoveField(
            model_name='imagehistogram',
            name='red_band',
        ),
    ]
