# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 09:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_compare', '0002_auto_20170605_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehistogram',
            name='alpha_band',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True), default=[0, 0, 0, 0], size=4),
        ),
        migrations.AddField(
            model_name='imagehistogram',
            name='blue_band',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=10), default=[0, 0, 0, 0], size=4),
        ),
        migrations.AddField(
            model_name='imagehistogram',
            name='green_band',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=10), default=[0, 0, 0, 0], size=4),
        ),
        migrations.AddField(
            model_name='imagehistogram',
            name='red_band',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=10), default=[0, 0, 0, 0], size=4),
        ),
    ]
