# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_compare', '0004_auto_20170605_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehistogram',
            name='alpha_band',
        ),
    ]
