# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_compare', '0005_remove_imagehistogram_alpha_band'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageHistogram',
            new_name='ImageMetadata',
        ),
    ]
