# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_compare', '0009_imagemetadata_norms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadata',
            name='norms',
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='norm',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
